#!/bin/bash
DEV=$1
VOLUMENAME=$(lsblk -ln -o LABEL $DEV)
true ${VOLUMENAME:=$(lsblk -ln -o PARTLABEL $DEV)}
true ${VOLUMENAME:=$(lsblk -ln -o VENDOR,MODEL ${DEV%%[0-9]*})}
true ${VOLUMENAME:=_}
VOLUMENAME=${VOLUMENAME//[[:space:]]/}
FILESYSTEM=$(lsblk -ln -o FSTYPE $DEV)
DRIVETYPE=$(lsblk -ln -o TRAN ${DEV%%[0-9]*})
VOLUMESERIALNUMBER=$(lsblk -ln -o UUID $DEV)
echo VOLUMENAME $VOLUMENAME
echo FILESYSTEM $FILESYSTEM
echo DRIVETYPE $DRIVETYPE
echo VOLUMESERIALNUMBER $VOLUMESERIALNUMBER


