SSH='ssh -i "/backup/bkit/scripts/client/conf/jvv/10.1.1.3/.priv/ssh.key" rsyncd@10.1.1.3 /bin/nc localhost 8761'
BACKUPURL='user@10.1.1.3::local.bKit-Office.033da664eaf277e22c92d04f57fd12b4.user.jvv'
PASSFILE='/backup/bkit/scripts/client/conf/jvv/10.1.1.3/.priv/secret'
UPDATERSRC=rsync://admin@10.1.1.3:8763/bkit-update/bKit-linux-x64/./
RSYNCOPTIONS=(
  --groupmap=4294967295:$(id -u)
  --usermap=4294967295:$(id -g)
  --numeric-ids
)
